[package]
name = "sexe_loader"
version = "0.1.0"
authors = ["Ben Weedon <ben@weedon.email>"]
edition = "2018"

[dependencies]
scopeguard = "1.1.0"
util = { path = "../util" }
uuid = { version = "0.8.1", features = ["v4"] }
winapi = { version = "0.3.9", features = ["wincon"] }
