[package]
name = "macros"
version = "0.1.3"
authors = ["Ben Weedon <ben@weedon.email>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.24"
quote = "1.0.7"
syn = "1.0.50"
